### PR TITLE
fix(postgresql): use default export 

### LINKED ISSUE #62: Postgres connector: The requested module 'pg' does not provide an export named 'Client'
### Environment

Node.js: Reproducible with `v18.18.0` and `v21.6.2`

db0@0.1.4
pg@8.11.3

### Reproduction

https://stackblitz.com/edit/github-xvw4kq?file=package.json

### Describe the bug

Given the following configuration:
```ts
import { defineNitroConfig } from 'nitropack/config';

export default defineNitroConfig({
  srcDir: 'server',
  experimental: {
    database: true,
  },
  database: {
    default: {
      connector: 'postgresql',
      options: {
        url: '',
      },
    },
  },
});
```

The server fails to start because the `Client` import from "pg" does not seem to be exported.

### Additional context


I'm not sure what's happening here, but I can run this with no issue.
```ts
// nitro.config.ts
import { Client } from "pg"
console.log(Client) // Works 👍🏻 
```

### Logs

```sh
ERROR  [worker reload] [worker init] The requested module 'pg' does not provide an export named 'Client'                                                                                                                                                                                                          2:03:46 PM

  import { Client } from "pg";
  ^^^^^^
  SyntaxError: The requested module 'pg' does not provide an export named 'Client'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
  at async loadESM (node:internal/process/esm_loader:28:7)
  at async handleMainPromise (node:internal/modules/run_main:120:12)

```
```

### PR DESCRIPTION
**Pull request by amandesai01**
### 🔗 Linked issue

Resolves #62

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Updated import statement for "pg" so that is works well with *.mjs files.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by fsyntax** [comment]
May I ask when this PR is going to get merged?

**Comment by amandesai01** [comment]
can we merge this? need this in a project.

**Comment by pi0** [comment]
sorry for delay but i need further testing to see either prefer this or `import * as` syntax (i understand it fixes nitro builds)

in the meantime i suggest to use pnpm patch.

**Comment by BlueBazze** [comment]
pi0 you have any updates or timeline for when you will look into this?

**Comment by danielroe** [comment]
arg - sorry for accidental click

**Comment by rafaelmagalhaes** [comment]
Hey what are the plans to release this ?

**Comment by joerosenthal** [comment]
Any updates on this? Currently having issues with using pg in a nuxt3 project on the nitro side of things—same failure to import: "The requested module 'pg' does not provide an export named 'Client'"

**Comment by BlueBazze** [comment]
> Any updates on this? Currently having issues with using pg in a nuxt3 project on the nitro side of things—same failure to import: "The requested module 'pg' does not provide an export named 'Client'"

Based on what I've seen and read.
Yes, pg is unusable until this is fixed. But keep in mind that it is an experimental feature, so it probably has a low priority.
Especially since they are in the middle of releasing nitro 3.0, and nuxt is working on nuxt 4.0
Nitro 3.0 was planned for the middle of june or july, so pi0 is likely working that.

**Comment by TimvdEijnden** [comment]
I also wanted to use db0 with postgres, but this is blocking me. @pi0 can you help a fellow Passionate Persion 😉

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks for fix PR and sorry it got this delayed. db0 was experimental and took less priority. it will get better attention.

**Pull request merged**
